import { ROLES } from './roles'

export const ALL_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.ADMIN,
  ROLES.CENTRAL_CHECKER,
  ROLES.DIVISIONAL_ADMIN,
  ROLES.DIVISIONAL_CHECKER,
  ROLES.REGIONAL_ADMIN,
  ROLES.REGIONAL_CHECKER,
  ROLES.BRANCH_ADMIN,
  ROLES.BRANCH_MANAGER,
  ROLES.BRANCH_EMPLOYEE,
]

export const ADMIN_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.ADMIN,
  ROLES.DIVISIONAL_ADMIN,
  ROLES.REGIONAL_ADMIN,
]

export const CHECKER_AND_ADMIN_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.ADMIN,
  ROLES.CENTRAL_CHECKER,
  ROLES.DIVISIONAL_ADMIN,
  ROLES.DIVISIONAL_CHECKER,
  ROLES.REGIONAL_ADMIN,
  ROLES.REGIONAL_CHECKER,
]

export const MENU_ITEMS = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    path: '/dashboard',
    icon: 'LayoutDashboard',
    roles: ALL_ROLES,
  },
  {
    id: 'form_builder',
    label: 'Form Builder',
    path: '/forms/builder',
    icon: 'FormInput',
    roles: ADMIN_ROLES,
  },
  {
    id: 'forms',
    label: 'Forms',
    path: '/forms',
    icon: 'ClipboardList',
    roles: ALL_ROLES,
  },
  {
    id: 'disburse_group',
    label: 'Disburse',
    icon: '💰',
    path: '#',
    roles: ALL_ROLES,
    children: [
      {
        id: 'form_new_loan',
        form_id: 'new-loan-disburse',
        label: 'New Loan Disburse',
        icon: '📌',
        path: '/forms/submit/new-loan-disburse',
        roles: ALL_ROLES,
      },
      {
        id: 'form_renew_loan',
        form_id: 'renew-loan-disburse',
        label: 'Renew Loan Disburse',
        icon: '📌',
        path: '/forms/submit/renew-loan-disburse',
        roles: ALL_ROLES,
      },
    ],
  },
  {
    id: 'recovery_group',
    label: 'Recovery',
    icon: '💰',
    path: '#',
    roles: ALL_ROLES,
    children: [
      {
        id: 'form_ss_recovery',
        form_id: 'ss-recovery',
        label: 'SS Recovery',
        icon: '📌',
        path: '/forms/submit/ss-recovery',
        roles: ALL_ROLES,
      },
      {
        id: 'form_df_recovery',
        form_id: 'df-recovery',
        label: 'DF Recovery',
        icon: '📌',
        path: '/forms/submit/df-recovery',
        roles: ALL_ROLES,
      },
      {
        id: 'form_test_1',
        form_id: 'test-form-1',
        label: 'টেস্ট ফর্ম',
        icon: '📌',
        path: '/forms/submit/test-form-1',
        roles: ALL_ROLES,
      },
      {
        id: 'form_test_2',
        form_id: 'test-form-2',
        label: 'টেস্ট ফর্ম 2',
        icon: '📌',
        path: '/forms/submit/test-form-2',
        roles: ALL_ROLES,
      },
    ],
  },
  {
    id: 'special_program_group',
    label: 'Special Program',
    icon: '📢',
    path: '#',
    roles: ALL_ROLES,
    children: [
      {
        id: 'form_amanat_week',
        form_id: 'amanat-week',
        label: 'Amanat Week',
        icon: '📌',
        path: '/forms/submit/amanat-week',
        roles: ALL_ROLES,
      },
    ],
  },
  {
    id: 'advanced_reports',
    label: 'Advanced Reports',
    path: '/advanced-reports',
    icon: 'BarChart2',
    roles: ALL_ROLES,
  },
  {
    id: 'submissions',
    label: 'All Submission',
    path: '/submissions',
    icon: 'Inbox',
    roles: ALL_ROLES,
  },
  {
    id: 'chat',
    label: 'Chat',
    path: '/chat',
    icon: 'Smartphone',
    roles: ALL_ROLES,
  },
  {
    id: 'audit_log',
    label: 'Audit Log',
    path: '/audit-logs',
    icon: 'ClipboardCheck',
    roles: ADMIN_ROLES,
  },
  {
    id: 'control_panel',
    label: 'Control Panel',
    icon: 'Settings',
    path: '#',
    roles: [
      ROLES.SUPER_ADMIN,
      ROLES.ADMIN,
      ROLES.DIVISIONAL_ADMIN,
      ROLES.REGIONAL_ADMIN,
      ROLES.REGIONAL_CHECKER,
    ],
    children: [
      {
        id: 'cp_users',
        label: 'Users',
        icon: 'Users',
        path: '/users',
        roles: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
      },
      {
        id: 'cp_branches',
        label: 'Branches',
        icon: 'GitBranch',
        path: '/branches',
        roles: [
          ROLES.SUPER_ADMIN,
          ROLES.ADMIN,
          ROLES.DIVISIONAL_ADMIN,
          ROLES.REGIONAL_ADMIN,
        ],
      },
      {
        id: 'cp_permissions',
        label: 'Permissions',
        icon: 'Shield',
        path: '/permissions',
        roles: [
          ROLES.SUPER_ADMIN,
          ROLES.ADMIN,
          ROLES.REGIONAL_ADMIN,
          ROLES.REGIONAL_CHECKER,
        ],
      },
      {
        id: 'cp_settings',
        label: 'Settings',
        icon: 'Sliders',
        path: '/settings',
        roles: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
      },
    ],
  },
]
