import { FlowBoardTool } from "../types";

export const DEFAULT_FLOW_TOOLS: FlowBoardTool[] = [
  {
    id: "budget-expense",
    name: "Office Allocation & Expense Management",
    nameBn: "অফিস বরাদ্দ ও ব্যয় ব্যবস্থাপনা সিস্টেম",
    description: "End-to-end financial budgeting, allocation tracking, expense vouchers, automatic note sheet generation, and multi-office audit records.",
    descriptionBn: "অফিসভিত্তিক বাজেট বরাদ্দ, ব্যয় ভাউচার দাখিল, স্বয়ংক্রিয় নোটশিট প্রণয়ন ও হিসাব নিরীক্ষা ব্যবস্থাপনা।",
    category: "finance",
    icon: "Coins",
    color: "#059669",
    gradient: "from-emerald-600 via-teal-600 to-cyan-700",
    badge: "Flagship Suite",
    badgeBn: "প্রধান ওয়ার্কস্পেস",
    version: "2.5.0",
    isDefault: true,
    status: "active",
    routeOrTab: "dashboard",
    statsCountKey: "expenses",
    tags: ["Budget", "Expense", "NoteSheets", "Vouchers", "Auditing"],
    subModules: [
      {
        id: "sub-postfacto",
        name: "Post-Facto Sanction",
        nameBn: "খরচোত্তর প্রস্তাব ও মঞ্জুরি",
        tab: "postfacto-propose",
        icon: "FileCheck2",
        badge: "Sanctions",
        badgeBn: "মঞ্জুরি",
      },
      {
        id: "sub-notesheets",
        name: "Note Sheet Studio",
        nameBn: "ডিজিটাল নোট শিট ও প্যাড",
        tab: "notesheets",
        icon: "FileText",
        badge: "Pad & Docx",
        badgeBn: "নোট ও প্যাড",
      },
      {
        id: "sub-analytics",
        name: "Financial Analytics",
        nameBn: "আর্থিক বিশ্লেষণ ও নিরীক্ষক",
        tab: "reports",
        icon: "BarChart3",
        badge: "Audit & Charts",
        badgeBn: "এনালিটিক্স",
      },
    ],
    createdBy: "System",
    createdAt: "2026-01-01",
  },
  {
    id: "stockpro",
    name: "StockPro Inventory & Voucher Tracker",
    nameBn: "স্টকপ্রো ইনভেন্টরি ট্র্যাকার",
    description: "Central inventory management, catalog records, branch requisition, distribution, and voucher stock ledger tracking.",
    descriptionBn: "কেন্দ্রীয় স্টক ইনভেন্টরি, ক্যাটালগ রেকর্ড, শাখাভিত্তিক মালামাল বিতরণ ও ভাউচার স্টক ট্র্যাকিং সিস্টেম।",
    category: "finance",
    icon: "Package",
    color: "#3b82f6",
    gradient: "from-blue-600 via-indigo-600 to-purple-700",
    badge: "Inventory & Stock",
    badgeBn: "ইনভেন্টরি ট্র্যাকার",
    version: "5.2.0",
    isDefault: false,
    status: "active",
    routeOrTab: "stockpro",
    tags: ["StockPro", "Inventory", "Vouchers", "Branches", "StockTracking"],
    createdBy: "System",
    createdAt: "2026-01-01",
  },
  {
    id: "conference-note",
    name: "Conference Bill & Note Generator",
    nameBn: "সভার নোট জেনারেটর",
    description: "Workshop, conference & meeting expense note sheets, automated agenda minutes drafting, and official note pads.",
    descriptionBn: "মিটিং, কর্মশালা ও কনফারেন্স সংক্রান্ত ব্যয় ভাউচার, স্বয়ংক্রিয় সভার কার্যবিবরণী ও নোটশিট ড্রাফটিং স্টুডিও।",
    category: "documents",
    icon: "FileSpreadsheet",
    color: "#d97706",
    gradient: "from-amber-600 via-orange-600 to-yellow-600",
    badge: "Meeting & Notes",
    badgeBn: "সভা ও নোট",
    version: "3.2.0",
    isDefault: false,
    status: "active",
    routeOrTab: "conference-note",
    tags: ["Conference", "Meeting", "NoteSheet", "Minutes", "Vouchers"],
    createdBy: "System",
    createdAt: "2026-01-01",
  },
  {
    id: "multi-item-bill",
    name: "Multi-Item Bill & CS Generator",
    nameBn: "বহু-আইটেম বিল ও কোটেশন বিবরণী",
    description: "Multi-item comparative statements (CS), bidder quotation evaluation, and automated purchase approval sheets.",
    descriptionBn: "একাধিক আইটেমের তুলনামূলক দরপত্র বিবরণী (CS), দরদাতা কোটেশন মূল্যায়ন ও অনুমোদিত বিল ভাউচার প্রস্তুতকারক।",
    category: "finance",
    icon: "Receipt",
    color: "#0891b2",
    gradient: "from-cyan-600 via-teal-600 to-blue-700",
    badge: "CS & Bill",
    badgeBn: "বিল ও CS",
    version: "4.0.0",
    isDefault: false,
    status: "active",
    routeOrTab: "multi-item-bill",
    tags: ["MultiItem", "Quotation", "ComparativeStatement", "BillApproval"],
    createdBy: "System",
    createdAt: "2026-01-01",
  },
  {
    id: "stationery-bill",
    name: "Printed Stationery & Work Order Challan",
    nameBn: "মুদ্রিত স্টেশনারী ও কার্যাদেশ চালান",
    description: "Bank official printing stationery, registers, ledgers work orders, delivery challan verification, and supplier billing.",
    descriptionBn: "ব্যাংক ফরম, রেজিস্টার ও প্রিন্টিং স্টেশনারী কার্যাদেশ, চালান গ্রহণ এবং সরবরাহকারী বিল সমন্বয় ব্যবস্থাপনা।",
    category: "documents",
    icon: "Printer",
    color: "#8b5cf6",
    gradient: "from-purple-600 via-indigo-600 to-violet-800",
    badge: "Work Order",
    badgeBn: "কার্যাদেশ ও চালান",
    version: "3.5.0",
    isDefault: false,
    status: "active",
    routeOrTab: "stationery-bill",
    tags: ["Stationery", "WorkOrder", "Challan", "PrintOrders", "Suppliers"],
    createdBy: "System",
    createdAt: "2026-01-01",
  },
  {
    id: "miscellaneous",
    name: "Miscellaneous & Form Overlay Studio",
    nameBn: "বিবিধ ও ফর্ম ওভারলে স্টুডিও",
    description: "Official form templates, Word & image overlay form designer, draggable text fields, stamps, and printable document tools.",
    descriptionBn: "অফিসিয়াল ফর্ম টেমপ্লেট, ওয়ার্ড ও ছবি ওভারলে ফিল্ড বিল্ডার, সিল ও ড্রাগেবল টেক্সট স্ট্যাম্পিং এবং প্রিন্টেবল বিবিধ টুলস।",
    category: "documents",
    icon: "Layers",
    color: "#6366f1",
    gradient: "from-indigo-600 via-purple-600 to-pink-700",
    badge: "Forms & Overlay",
    badgeBn: "ফরম ও ওভারলে",
    version: "2.0.0",
    isDefault: false,
    status: "active",
    routeOrTab: "miscellaneous",
    tags: ["Miscellaneous", "Forms", "Overlay", "Templates", "Pad", "Docx"],
    createdBy: "System",
    createdAt: "2026-01-01",
  },
  {
    id: "office-monitoring",
    name: "Office Monitoring Management System",
    nameBn: "অফিস মনিটরিং ম্যানেজমেন্ট সিস্টেম",
    description: "Centralized office monitoring, form submissions, multi-tier approvals, branch reports, audit logs, and hierarchy management.",
    descriptionBn: "কেন্দ্রীয় অফিস মনিটরিং, শাখাভিত্তিক তথ্য রিপোর্ট, বহুস্তরীয় অনুমোদন ব্যবস্থা, নিরীক্ষা লগ ও বিভাগীয়/আঞ্চলিক ব্যবস্থাপনা।",
    category: "compliance",
    icon: "ShieldCheck",
    color: "#cc785c",
    gradient: "from-amber-600 via-orange-600 to-rose-700",
    badge: "Data & Reports",
    badgeBn: "ডাটা ও রিপোর্ট",
    version: "1.0.0",
    isDefault: false,
    status: "active",
    routeOrTab: "office-monitoring",
    tags: ["OfficeMonitoring", "Reports", "Submissions", "Approvals", "Audit", "Hierarchy", "Branches"],
    createdBy: "System",
    createdAt: "2026-01-01",
  },
];

export const CATEGORY_LABELS: Record<string, { en: string; bn: string; color: string; bg: string }> = {
  all: { en: "All Tools", bn: "সকল টুল", color: "text-slate-700", bg: "bg-slate-100 dark:bg-slate-800 text-slate-900 dark:text-white" },
  finance: { en: "Finance & Accounts", bn: "অর্থ ও হিসাব", color: "text-emerald-600", bg: "bg-emerald-50 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300" },
  documents: { en: "Documents & Notes", bn: "নোট ও ডকুমেন্টস", color: "text-indigo-600", bg: "bg-indigo-50 text-indigo-700 dark:bg-indigo-950/40 dark:text-indigo-300" },
  compliance: { en: "Compliance & Sanctions", bn: "অনুমোদন ও কমপ্লায়েন্স", color: "text-amber-600", bg: "bg-amber-50 text-amber-700 dark:bg-amber-950/40 dark:text-amber-300" },
  analytics: { en: "Analytics & Audit", bn: "অডিট ও এনালিটিক্স", color: "text-cyan-600", bg: "bg-cyan-50 text-cyan-700 dark:bg-cyan-950/40 dark:text-cyan-300" },
  custom: { en: "Custom Modules", bn: "কাস্টম মডিউল", color: "text-purple-600", bg: "bg-purple-50 text-purple-700 dark:bg-purple-950/40 dark:text-purple-300" },
};
